- name: Add authorized keys to Ansible user
  connection: ssh
  authorized_key:
    user: "{{ ansible_user_2 }}"
    key: "{{ ansible_authorized_keys }}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
     # 86400 seconds = 24 hours
    cache_valid_time: 86400

- name: Install common packages
  apt:
    name: ['acl', 'aptitude', 'apt-show-versions', 'bzip2', 'cron-apt', 'debconf-utils', 'fail2ban', 'git', 'htop', 'iotop', 'iptables-persistent', 'mtr-tiny', 'ncdu', 'nmap', 'python3-dbus', 'screen', 'sudo', 'sysstat', 'tree', 'unzip', 'vim', 'zip', 'zsh', 'silversearcher-ag', 'colordiff']
    state: present
    # 86400 seconds = 24 hours
    cache_valid_time: 86400
  tags: [packages, configuration]
  when: ansible_os_family =="Debian"

- name: default to Python3
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
    priority: 1

- name: Configure the hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ fqdn }} {{ hostname }}"
  tags: [hostname, configuration]

# FIXME: This failed on my last Koumbit install, maybe they control this?  Seems weird because root access.
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags: [hostname, configuration]

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  notify:
    - restart crond
  tags: [timezone, configuration]

- name: Add gitea keys to Ansible user known_hosts
  known_hosts:
    name: "[git.megaphonetech.com]:10022"
    key: "{{ inner_item }}"
  loop_control:
    loop_var: inner_item
  with_items:
    - "[git.megaphonetech.com]:10022 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgNwIe3TBtRHtkwoHL2TG84/f039hgzqVbN0z4sk1UHPZr4rxFinGCGjedzE+adVucqr/gemPnETfashTujcPyZZkwPn2dQNx0HuPHw3H+cqXqKt03fsgPcerqsqvFS509pcblmP5vtJLF4uVgbh6TLmZiObMuiIYe9VTyZSXo67DTt/K6SSgwyUFldqJIJQA+DO1nXoSYSJ4fP1DDPdue0RTL06VtlnUL2w9iHrOgVRY1KqAtpnGRslKx5c3L8+9EBMdJWM1CPK11vkvyf8LnYwuCH4V7w0rVs2QAE9Abm4g4HiE4wql5QJrjCi/cq/1doeY9KXxFb8SOTtZBk5Nn"
    - "[git.megaphonetech.com]:10022 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLuEP2fW8Eycdbeo0XWihr63zj6yCTcCjxh4C4i3c8p2O44mKRjVhxOSSBQQxZNUKeJYAGTuWh+EPW71KADzXv0="
    - "[git.megaphonetech.com]:10022 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJoN1UsqLqucSJo4dSum6Xy2qCrlutDAu3wPdprAL4w"
  become_user: "{{ ansible_user }}"

# TODO: Is this actually necessary?
- name: Add the rsync.net public hostkey to known_hosts
  known_hosts:
    key: "{{ rsyncnet_public_hostkey }}"
    name: usw-s008.rsync.net
  become_user: "{{ ansible_user }}"

- name: Add the rsync.net public hostkey to known_hosts
  known_hosts:
    key: "{{ rsyncnet_public_hostkey }}"
    name: usw-s008.rsync.net
  become_user: root
